name: HelloWorld

author: ML
website:
main: HelloWorldPlugin

commands:
    hello:
        description: Say Hello to everyone!
        usage: /hello

    killplayer:
        description: Kills a specified player!
        usage: /killplayer <playername>

version: 0.1
